configurations:
  # CommunicationKit
  - sources:
      - ../CommunicationKit
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../CommunicationKit/Mocks/Generated.swift
    args:
        imports:
          - CommunicationKitInterface
  # DBKit
  # EnigneKit
  - sources:
      - ../EngineKit/Sources/AppearanceService
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/AppearanceService/Mocks/Generated.swift
    args:
        imports:
          - AppearanceServiceInterface

  - sources:
      - ../EngineKit/Sources/DateService
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/DateService/Mocks/Generated.swift
    args:
        imports:
          - DateServiceInterface

  - sources:
      - ../EngineKit/Sources/DayService
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
    output: ../EngineKit/Sources/DayService/Mocks/Generated.swift
    args:
        imports:
          - DayServiceInterface
          - DrinkServiceInterface

  - sources:
      - ../EngineKit/Sources/DrinkService
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/DrinkService/Mocks/Generated.swift
    args:
        imports:
          - DrinkServiceInterface

  - sources:
      - ../EngineKit/Sources/LanguageService
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/LanguageService/Mocks/Generated.swift
    args:
        imports:
          - LanguageServiceInterface

  - sources:
      - ../EngineKit/Sources/UserNotificationService
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/UserNotificationService/Mocks/Generated.swift
    args:
        imports:
          - UserNotificationServiceInterface

  - sources:
      - ../EngineKit/Sources/UserPreferenceService
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/UserPreferenceService/Mocks/Generated.swift
    args:
        imports:
          - UserPreferenceServiceInterface

  - sources:
      - ../EngineKit/Sources/UnitService
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/UnitService/Mocks/Generated.swift
    args:
        imports:
          - UnitServiceInterface

  - sources:
      - ../EngineKit/Sources/TimelineService
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/TimelineService/Mocks/Generated.swift
    args:
        imports:
          - TimelineServiceInterface

  - sources:
      - ../EngineKit/Sources/Ports
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/Ports/Mocks/Generated.swift
    args:
        imports:
          - PortsInterface

  - sources:
      - ../EngineKit/Sources/PhoneComms
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/PhoneComms/Mocks/Generated.swift
    args:
        imports:
          - PhoneCommsInterface

  - sources:
      - ../EngineKit/Sources/WatchComms
    templates:
      - Templates/AutoStub.stencil
      - Templates/AutoSpy.stencil
      - Templates/AutoString.stencil
      - Templates/AutoEquatable.stencil
    output: ../EngineKit/Sources/WatchComms/Mocks/Generated.swift
    args:
        imports:
          - WatchCommsInterface

  # EnigneMocks
  - sources:
      - ../EngineKit/Sources/EngineMocks
    templates:
      - Templates/AutoMock.stencil
    output: ../EngineKit/Sources/EngineMocks/Generated.swift
    args:
        imports:
          - AppearanceServiceInterface
          - AppearanceServiceMocks
          - DBKitInterface
          - DBKitMocks
          - DateServiceInterface
          - DateServiceMocks
          - DayServiceInterface
          - DayServiceMocks
          - DrinkServiceInterface
          - DrinkServiceMocks
          - LanguageServiceInterface
          - LanguageServiceMocks
          - LoggingService
          - UserNotificationServiceInterface
          - UserNotificationServiceMocks
          - UnitServiceInterface
          - UnitServiceMocks
          - UserPreferenceServiceInterface
          - UserPreferenceServiceMocks
          - PortsInterface
          - PortsMocks

# PresentationKit
# PresentationWatchKit
