configurations:
# DBKit
# EnigneKit
  - sources:
      - ../EngineKit/Sources/AppearanceService
    templates:
      - Templates/AutoStub.stencil
    output: ../EngineKit/Sources/AppearanceService/Mocks/Generated/AppearanceServiceStub.swift
    args: 
      imports: 
        - AppearanceServiceInterface

  - sources:
        - ../EngineKit/Sources/DateService
    templates:
        - Templates/AutoStub.stencil
    output: ../EngineKit/Sources/DateService/Mocks/Generated/DateServiceStub.swift
    args: 
      imports: 
          - DateServiceInterface

  - sources:
        - ../EngineKit/Sources/DayService
    templates:
        - Templates/AutoStub.stencil
    output: ../EngineKit/Sources/DayService/Mocks/Generated/DayServiceStub.swift
    args: 
      imports: 
          - DayServiceInterface
          - DrinkServiceInterface

  - sources:
        - ../EngineKit/Sources/DrinkService
    templates:
        - Templates/AutoStub.stencil
    output: ../EngineKit/Sources/DrinkService/Mocks/Generated/DrinkServiceStub.swift
    args: 
      imports:
          - DrinkServiceInterface

  - sources:
        - ../EngineKit/Sources/LanguageService
    templates:
        - Templates/AutoStub.stencil
    output: ../EngineKit/Sources/LanguageService/Mocks/Generated/LanguageServiceStub.swift
    args: 
      imports:
          - LanguageServiceInterface

  - sources:
        - ../EngineKit/Sources/NotificationService
    templates:
        - Templates/AutoStub.stencil
    output: ../EngineKit/Sources/NotificationService/Mocks/Generated/NotificationServiceStub.swift
    args: 
      imports:
          - NotificationServiceInterface

  - sources:
        - ../EngineKit/Sources/UserPreferenceService
    templates:
        - Templates/AutoStub.stencil
    output: ../EngineKit/Sources/UserPreferenceService/Mocks/Generated/UserPreferenceServiceStub.swift
    args: 
      imports:
          - UserPreferenceServiceInterface
          
# PresentationKit
# PresentationWatchKit